# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Aspiring Shipping App"
client_id = "7066cb5cbde3e0b21fe0b2c6cce561a9"
application_url = "https://sum-gzip-favorites-powell.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_shipping,write_shipping"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://sum-gzip-favorites-powell.trycloudflare.com/auth/callback",
  "https://sum-gzip-favorites-powell.trycloudflare.com/auth/shopify/callback",
  "https://sum-gzip-favorites-powell.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-13915009.myshopify.com"
